<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>dashgo_xfeat_bringup</name>
  <version>0.0.0</version>
  <description>Standalone XFeat bringup package for the Dashgo real robot workspace.</description>
  <maintainer email="clibang2022@163.com">boxing</maintainer>
  <license>TODO: License declaration</license>

  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>message_filters</depend>
  <depend>cv_bridge</depend>
  <depend>rtabmap_msgs</depend>
  <depend>nav_msgs</depend>
  <depend>geometry_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>dashgo_driver_ros2</depend>
  <depend>dashgo_realsense_ros2</depend>
  <depend>nav_slam</depend>
  <exec_depend>rtabmap_launch</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
